language: c
compiler:
  - clang
  - gcc
dist: xenial
script:
  - make -C wpa_supplicant
addons:
  apt:
    packages:
      - libnl-genl-3-dev
      - libssl-dev
before_deploy:
  - "mkdir wpa_sycophant"
  - "cp wpa_sycophant.sh wpa_sycophant_example.conf wpa_supplicant/wpa_supplicant wpa_sycophant"
  - "tar -zcf wpa_sycophant.tar.gz wpa_sycophant"
deploy:
  provider: releases
  api_key:
    secure: "$API_KEY"
    # secure: bBG3MSYz1Z9h6OxHj7IopMTSvi/c+Qwyb/AJ/9ezk5dKv3V2Nu4pRGAOV4Wlcg6jeg6yNPiIHANLWISk81vD+Jt81S288O3PDxxa8SOp/U9dl7Fn3CoO7ubtOhCNXhOSyFbuOBkHJ20RbbHatj0suxQoYHd7ybllE+ZEvs48ZgXbj9JrLjSsaePEEemTT/HW8b29KJEdK6xIJuS+eFZI49mjKzbD0HQ4FRmm7c1P2jAFEO528txfNDJnaWfoMNuwUXZ6iXDW500oVIAP0fnx6VS8XqJpXtiiNSz+6PVuTevvaACoK07vr0n/nUqIOcCen7wCLoQ496PH2Kn7xfda7x9jcIDaigqROy8LO7HRRzN5nUYHuXA437SaYPTakqBkkBFKEXNA7DnTSszTVKPd6UKejW1DFV2ODG1t4itpcbsSXq+TrcS2g4kVEE1L3JDTCY2yhynAG2JsfytTcUwY59EtnecQE8u15i8XpGUiQy+3p0rBJSiSgrt9V60iriwYqex09EkdyOHe0sa/K0fgN3FAVqt6kmsN7LaVfn4U6yjYVP6AUXAIp7FRvbJjxEYiXsv8/mXsWiYjCAXqZJAMR+d8xRyHq7ortd7Lw3Yy56rGUDtDWndQz61XeObUZgMXumcI+ak2wxoSbE/XReyut2q1ky969BWN4nbMibj98J8=
  file: wpa_sycophant.tar.gz
  on:
    repo: Cablethief/wpa_sycophant
    # tags: true
    draft: true
    condition: "$CC = gcc"
    branch: master
  overwrite: true
  prerelease: true
  name: Nightly
  skip_cleanup: true
